env: "dev"
server:
  host: "localhost"
  port: 8081
  timeout: 4s
  idle_timeout: 60s
db:
  postgres:
    host: "db-payment"
    username: "postgres"
    password: "postgres"
    db_name: "iod_payment"
    port: 5432
    ssl_mode: "disable"
  redis:
    host: "redis-payment"
    port: 6379
    password: "12345678"
    protocol: 3
pay_api:
  shop_id: 994351
  secret_key: "test_MheegEXjJUlromDARVVTdiZrsGAB_8YBbgv17erGQ0A"
  payout_agent_id: 507516
  payout_secret_key: "test_*gQHvJHOOFcq0hKawwAcGdPYPuiPTDG2qcHHVdZxCCKCs"